namespace WinLedger.Domain.InstalledApplications;

public sealed record InstalledApplicationSnapshot(
    string Identity,
    InstalledApplicationScopeKind Scope,
    InstalledApplicationArchitectureKind Architecture,
    InstalledApplicationSourceKind Source,
    string RegistryKeyPath,
    string KeyName,
    string? ProductCode,
    string DisplayName,
    string? DisplayVersion,
    string? Publisher,
    string? InstallLocation,
    string? InstallSource,
    string? InstallDate,
    string? UninstallString,
    string? QuietUninstallString,
    string? ModifyPath,
    long? EstimatedSizeKb,
    bool WindowsInstaller,
    bool SystemComponent,
    string? ReleaseType,
    string? Comments,
    string? UrlInfoAbout,
    string? PackageFullName = null,
    string? PackageFamilyName = null,
    string? PackageName = null,
    string? PackagePublisherId = null,
    string? PackageResourceId = null,
    string? PackageManifestPath = null,
    bool AppxInboxPackage = false);
